sonar.projectKey=HopfieldAssigmentProblemSolver
sonar.projectName=Hopfield Assigment Problem Solver
sonar.projectVersion=1.0
sonar.sources=hopfield,api,scripts
sonar.tests=tests
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.host.url=http://192.168.1.86:9000
sonar.login=admin
sonar.password=patilla1
